# Generated by Django 2.2.16 on 2025-03-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosting', models.CharField(help_text='hebergement', max_length=100)),
                ('meal', models.CharField(help_text='repas', max_length=100)),
                ('transport', models.CharField(help_text='transport', max_length=100)),
                ('various_expenses', models.CharField(help_text='divers frais', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='nom du technicien', max_length=50)),
                ('last_name', models.CharField(help_text='prenom du technicien', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_details', models.TextField(help_text='details de la mission', verbose_name='Mission Details')),
                ('start_date', models.DateField(help_text='date de debut de la mission', verbose_name='Start Date')),
                ('start_hour', models.TimeField(help_text='heure de debut de la mission', verbose_name='Start Hour')),
                ('end_date', models.DateField(help_text='date de fin de la mission', verbose_name='End Date')),
                ('end_hour', models.TimeField(help_text='heure de fin de la mission', verbose_name='End Hour')),
                ('location', models.CharField(help_text='lieu de la mission', max_length=50)),
                ('facturation', models.BooleanField(help_text='facturation de la mission, facturee ou non', verbose_name='Facturation')),
                ('technician', models.ManyToManyField(help_text='technicien de la mission', to='fdm_app.Technician')),
            ],
        ),
    ]
