# Generated by Django 2.2.16 on 2025-03-10 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdm_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='technician',
        ),
    ]
