# Generated by Django 2.2.16 on 2025-03-10 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdm_app', '0002_remove_mission_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='fdm_app.Mission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='techniciens',
            field=models.ManyToManyField(related_name='missions', to='fdm_app.Technician'),
        ),
    ]
