# Generated by Django 2.2.16 on 2025-03-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdm_app', '0003_auto_20250310_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='various_expenses',
            new_name='various_expenses_details',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='hosting',
        ),
        migrations.AddField(
            model_name='expense',
            name='Total_hosting',
            field=models.DecimalField(decimal_places=2, default=0, help_text=' pris total de sejour', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='hosting_days',
            field=models.IntegerField(default=0.0, help_text='nombre de jours de sejour'),
        ),
        migrations.AddField(
            model_name='expense',
            name='overnight_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='tarif nuit', max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='shipping_costs',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='frais de transport', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='various_expenses_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='prix des divers frais', max_digits=10),
            preserve_default=False,
        ),
    ]
