# Generated by Django 2.2.16 on 2025-03-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdm_app', '0005_auto_20250311_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='total_hosting',
            field=models.DecimalField(decimal_places=2, editable=False, help_text=' pris total de sejour', max_digits=10),
        ),
    ]
