# Generated by Django 2.2.16 on 2025-03-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdm_app', '0006_auto_20250311_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='meal',
        ),
        migrations.AddField(
            model_name='expense',
            name='meal_costs',
            field=models.CharField(default=0.0, help_text='pris repas/jours', max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='prix total des frais', max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='total_meal_costs',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='prix total des repas', max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='overnight_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='tarif nuitée', max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='total_hosting',
            field=models.DecimalField(decimal_places=2, editable=False, help_text=' pris total de séjour', max_digits=10),
        ),
    ]
