# Generated by Django 2.2.16 on 2025-03-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdm_app', '0007_auto_20250311_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='meal_costs',
            field=models.DecimalField(decimal_places=2, help_text='prix des repas', max_digits=10),
        ),
    ]
