# Generated by Django 2.2.16 on 2025-03-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdm_app', '0008_auto_20250311_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('REFUSED', 'Refused'), ('VALIDATED', 'Validated')], default='NEW', help_text='Statut de la mission', max_length=10, verbose_name='Status'),
        ),
    ]
