# Generated by Django 2.2.16 on 2025-03-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdm_app', '0010_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='refusal_reason',
            field=models.TextField(blank=True, help_text='Motif de refus de la mission', null=True, verbose_name='Refusal Reason'),
        ),
    ]
