# Generated by Django 2.2.16 on 2025-04-08 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fdm_app', '0011_mission_refusal_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date et heure de création de la mission', verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='refused_at',
            field=models.DateTimeField(blank=True, help_text='Date et heure de refus de la mission', null=True, verbose_name='Date de refus'),
        ),
        migrations.AddField(
            model_name='mission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification de la mission', verbose_name='Date de modification'),
        ),
        migrations.AddField(
            model_name='mission',
            name='validated_at',
            field=models.DateTimeField(blank=True, help_text='Date et heure de validation de la mission', null=True, verbose_name='Date de validation'),
        ),
    ]
