# Generated by Django 2.2.16 on 2025-04-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdm_app', '0012_auto_20250408_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='bluedesk_link',
            field=models.CharField(default='https://bluedesk.example.com', help_text='lien bluedesk', max_length=300, verbose_name='Bluedesk Link'),
        ),
    ]
