# Generated by Django 2.2.16 on 2025-04-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdm_app', '0013_mission_bluedesk_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'permissions': [('can_validate_mission', 'Peut valider une mission'), ('can_refuse_mission', 'Peut refuser une mission')]},
        ),
    ]
