# Generated by Django 5.2.1 on 2025-05-12 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='nom du technicien', max_length=50)),
                ('last_name', models.CharField(help_text='prenom du technicien', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bluedesk_link', models.CharField(default='https://bluedesk.example.com', help_text='lien bluedesk', max_length=300, verbose_name='Bluedesk Link')),
                ('mission_details', models.TextField(help_text='details de la mission', verbose_name='Mission Details')),
                ('start_date', models.DateField(help_text='date de debut de la mission', verbose_name='Start Date')),
                ('start_hour', models.TimeField(help_text='heure de debut de la mission', verbose_name='Start Hour')),
                ('end_date', models.DateField(help_text='date de fin de la mission', verbose_name='End Date')),
                ('end_hour', models.TimeField(help_text='heure de fin de la mission', verbose_name='End Hour')),
                ('location', models.CharField(help_text='lieu de la mission', max_length=50)),
                ('facturation', models.BooleanField(help_text='facturation de la mission, facturee ou non', verbose_name='Facturation')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REFUSED', 'Refused'), ('VALIDATED', 'Validated')], default='NEW', help_text='Statut de la mission', max_length=10, verbose_name='Status')),
                ('refusal_reason', models.TextField(blank=True, help_text='Motif de refus de la mission', null=True, verbose_name='Refusal Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création de la mission', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification de la mission', verbose_name='Date de modification')),
                ('validated_at', models.DateTimeField(blank=True, help_text='Date et heure de validation de la mission', null=True, verbose_name='Date de validation')),
                ('refused_at', models.DateTimeField(blank=True, help_text='Date et heure de refus de la mission', null=True, verbose_name='Date de refus')),
                ('created_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a créé la mission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('techniciens', models.ManyToManyField(related_name='missions', to='frais_app.technician')),
            ],
            options={
                'permissions': [('can_validate_mission', 'Peut valider une mission'), ('can_refuse_mission', 'Peut refuser une mission')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosting_days', models.IntegerField(default=1, help_text='nombre de jours de sejour')),
                ('overnight_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='tarif nuitée', max_digits=10)),
                ('total_hosting', models.DecimalField(decimal_places=2, editable=False, help_text=' pris total de séjour', max_digits=10)),
                ('meal_costs', models.DecimalField(decimal_places=2, default=0.0, help_text='prix des repas', max_digits=10)),
                ('total_meal_costs', models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='prix total des repas', max_digits=10)),
                ('transport', models.CharField(help_text='transport', max_length=100)),
                ('shipping_costs', models.DecimalField(decimal_places=2, default=0.0, help_text='frais de transport', max_digits=10)),
                ('various_expenses_details', models.CharField(help_text='divers frais', max_length=100)),
                ('various_expenses_price', models.DecimalField(decimal_places=2, default=0.0, help_text='prix des divers frais', max_digits=10)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='prix total des frais', max_digits=10)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='frais_app.mission')),
            ],
        ),
        migrations.CreateModel(
            name='MissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mission_files/%Y/%m/%d/', verbose_name='Fichier')),
                ('file_description', models.CharField(default='Pas de description du fichier', help_text='description du fichier', max_length=100, verbose_name='File Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='frais_app.mission')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
