# Generated by Django 5.2.1 on 2025-05-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frais_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('REFUSED', 'Refused'), ('VALIDATED', 'Validated'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='NEW', help_text='Statut de la mission', max_length=30, verbose_name='Status'),
        ),
    ]
