# Generated by Django 5.2.1 on 2025-05-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frais_app', '0003_alter_mission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Date et heure de clôture de la mission', null=True, verbose_name='Date de clôture'),
        ),
    ]
