# Generated by Django 5.2.1 on 2025-05-19 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frais_app', '0004_mission_closed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'permissions': [('can_validate_mission', 'Peut valider une mission'), ('can_refuse_mission', 'Peut refuser une mission'), ('can_close_mission', 'Peut cloturer une mission')]},
        ),
    ]
