# Generated by Django 5.2.1 on 2025-05-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frais_app', '0005_alter_mission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='matricule',
            field=models.CharField(blank=True, help_text='matricule du technicien', max_length=50, null=True),
        ),
    ]
