# Generated by Django 5.2.1 on 2025-06-04 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frais_app', '0006_technician_matricule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'permissions': [('can_validate_mission', 'Peut valider une mission'), ('can_refuse_mission', 'Peut refuser une mission'), ('can_edit_mission', 'Peut modifier une mission'), ('can_close_mission', 'Peut cloturer une mission'), ('can_upload_file', 'Peut uploader un fichier'), ('can_create_technician', 'Peut creer un technicien')]},
        ),
        migrations.AddField(
            model_name='mission',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant dernièrement modifié la mission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='missionfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_files_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par'),
        ),
    ]
