services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    image: frais_mission_web_prod
    container_name: frais_mission_web_prod
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    restart: always
  
  db:
    image: postgres:15
    container_name: frais_mission_db_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "55433:5432"
    restart: always

  nginx:
    build: ./nginx
    image: frais_mission_nginx
    container_name: frais_mission_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static_data:
  media_data:

    